'\" t
.\"     Title: automx_script
.\"    Author: Christian Roessner <cr@sys4.de>
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 02/01/2013
.\"    Manual: automx_script
.\"    Source: Version 0.9.1
.\"  Language: English
.\"
.TH "AUTOMX_SCRIPT" "5" "02/01/2013" "Version 0.9.1" "automx_script"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
automx_script \- automx script backend configuration parameters
.SH "DESCRIPTION"
.PP
The
\fBautomx_script\fR(5)
man page specifies all parameters that control access from within
automx
to a script backend\&.
.PP
The script backend provides automx with configuration values by running an external script\&. The results of the script are handed back to automx\&. automx assigns the results as values to account configuration parameters\&.
.SH "PARAMETERS"
.PP
\fBresult_attrs\fR (default: none)
.RS 4
Specifies a list of one or more variables\&. The output of the external script will assign values to these variables\&. Results will be assigned in the same order as variables have been listed\&.
.sp
.if n \{\
.RS 4
.\}
.nf
result_attrs = server, email, auth, socket
.fi
.if n \{\
.RE
.\}
.if n \{\
.sp
.\}
.RS 4
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.ps +1
\fBImportant\fR
.ps -1
.br
\fBautomx_script\fR(5)
does not check if the number of values returned matches the ones expected\&. Too many return values will be discarded\&. If the script returns too few
\fBautomx_script\fR(5)
will use the corresponding result attribute name\&.
.sp .5v
.RE
.RE
.PP
\fBscript\fR (default: none)
.RS 4
Specifies the absolute path to the script which should be run by the backend
\fBautomx_script\fR(5)
backend\&.
.sp
.if n \{\
.RS 4
.\}
.nf
script = /usr/local/bin/example_com\&.sh "%s"
.fi
.if n \{\
.RE
.\}
.RE
.PP
\fBseparator\fR (default: whitespace)
.RS 4
Specifies the character that separates values returned by the external script\&.
.sp
.if n \{\
.RS 4
.\}
.nf
separator = ,
.fi
.if n \{\
.RE
.\}
.RE
.SH "SEE ALSO"
.PP
\fBautomx\fR(8),
\fBautomx.conf\fR(5),
\fBautomx_ldap\fR(5),
\fBautomx_script\fR(5),
\fBautomx_sql\fR(5),
\fBautomx-test\fR(1)
.SH "AUTHORS"
.PP
\fBChristian Roessner\fR <\&cr@sys4\&.de\&>
.RS 4
Wrote the program\&.
.RE
.PP
\fBMichael Menge\fR
.RS 4
Wrote and contributed this backend\&.
.RE
.PP
\fBPatrick Ben Koetter\fR <\&p@sys4\&.de\&>
.RS 4
Wrote the documentation\&.
.RE
