'\" t
.\"     Title: automx_ldap
.\"    Author: Christian Roessner <cr@sys4.de>
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 02/01/2013
.\"    Manual: automx_ldap
.\"    Source: Version 0.9.1
.\"  Language: English
.\"
.TH "AUTOMX_LDAP" "5" "02/01/2013" "Version 0.9.1" "automx_ldap"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
automx_ldap \- automx LDAP backend configuration parameters
.SH "DESCRIPTION"
.PP
The
\fBautomx_ldap\fR(5)
man page specifies all parameters that control access from within
automx
to a LDAP backend\&.
.SH "PARAMETERS"
.PP
\fBauthzid\fR (no default)
.RS 4
Specifies the SASL proxy authorization identity\&.
.RE
.PP
\fBbase\fR (default: none)
.RS 4
Specifies the default base DN to use when performing ldap operations\&. The base must be specified as a Distinguished Name in LDAP format\&.
.RE
.PP
\fBbinddn\fR (default: none)
.RS 4
Specifies the default bind DN to use when performing ldap operations\&. The bind DN must be specified as a Distinguished Name in LDAP format\&.
.RE
.PP
\fBbindmethod\fR (default: \fIsimple\fR)
.RS 4
Specifies how authentication should take place\&. Valid options are either
\fIsimple\fR
for a simple bind or
\fIsasl\fR
for a bind that requires SASL authentication\&.
.RE
.PP
\fBbindpw\fR (default: none)
.RS 4
Specifies the password used when
\fBbinddn\fR
identifies itself with the LDAP server\&.
.RE
.PP
\fBcacert\fR (default: none)
.RS 4
Specifies the path to a file that contains all certificates of Certification Authorities automx should trust\&.
.RE
.PP
\fBcert\fR (default: none)
.RS 4
Specifies the path to a file that contains automx\*(Aqs certificate\&.
.RE
.PP
\fBcipher\fR (default: \fITLSv1\fR)
.RS 4
See
\fBciphers\fR(1)
for a list of valid options\&.
.RE
.PP
\fBfilter\fR (default: \fI(objectClass=*)\fR)
.RS 4
Specifies the search filter to select appropriate LDAP objects\&. The filter should conform to the string representation for search filters as defined in RFC 4515\&.
.if n \{\
.sp
.\}
.RS 4
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.ps +1
\fBNote\fR
.ps -1
.br
See the section
\(lqMacros and Variables\(rq
in
\fBautomx.conf\fR(5)
for a list of available query macros\&.
.sp .5v
.RE
.RE
.PP
\fBhost\fR (default: \fIldap://127\&.0\&.0\&.1/\fR)
.RS 4
Specifies one or more LDAP servers separated by commas as shown in the following example:
.sp
.if n \{\
.RS 4
.\}
.nf
host = ldap://127\&.0\&.0\&.1, ldap://192\&.168\&.2\&.1
.fi
.if n \{\
.RE
.\}
.if n \{\
.sp
.\}
.RS 4
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.ps +1
\fBListing two and more servers\fR
.ps -1
.br
Subsequent servers to the first serve
\fIonly for fallback purposes\fR, i\&.e\&. a server to the right will only be queried if the server left to it cannot be reached\&. If a server can be reached no further attempts will be made regardless if the query returned a result or not\&.
.sp .5v
.RE
.RE
.PP
\fBkey\fR (default: none)
.RS 4
Specifies the path to a file that contains automx\*(Aqs private key, which matches automx certificate given with
\fBcert\fR\&.
.RE
.PP
\fBreqcert\fR (default: \fInever\fR)
.RS 4
Specifies what checks to perform on server certificates in a TLS session, if any\&. The <level> can be specified as one of the following keywords:
.PP
never
.RS 4
The client will not request or check any server certificate\&. This is the default setting\&.
.RE
.PP
allow
.RS 4
The server certificate is requested\&. If no certificate is provided, the session proceeds normally\&. If a bad certificate is provided, it will be ignored and the session proceeds normally\&.
.RE
.PP
try
.RS 4
The server certificate is requested\&. If no certificate is provided, the session proceeds normally\&. If a bad certificate is provided, the session is immediately terminated\&.
.RE
.PP
demand
.RS 4
These keywords are equivalent\&. The server certificate is requested\&. If no certificate is provided, or a bad certificate is provided, the session is immediately terminated\&.
.RE
.RE
.PP
\fBresult_attrs\fR (default: none)
.RS 4
If automx finds one or more entries, the attributes specified by result_attrs are returned\&. If * is listed, all user attributes are returned\&.
.RE
.PP
\fBsaslmech\fR (default: none)
.RS 4
Specifies the SASL mechanism to be used for authentication\&.
.PP
cram\-md5
.RS 4
The SASL
\fIcram\-md5\fR
mechanism (see:
\m[blue]\fBRFC 2195\fR\m[]\&\s-2\u[1]\d\s+2) will be used to authenticate LDAP bind requests\&.
.RE
.PP
digest\-md5
.RS 4
The SASL
\fIdigest\-md5\fR
mechanism (see:
\m[blue]\fBRFC 2831\fR\m[]\&\s-2\u[2]\d\s+2) will be used to authenticate LDAP bind requests\&.
.RE
.PP
external
.RS 4
The SASL
\fIexternal\fR
mechanism (see:
\m[blue]\fBRFC 4422\fR\m[]\&\s-2\u[3]\d\s+2) will be used to authenticate LDAP bind requests\&.
.RE
.PP
gssapi
.RS 4
The SASL
\fIgssapi\fR
mechanism (see:
\m[blue]\fBRFC 4752\fR\m[]\&\s-2\u[4]\d\s+2) will be used to authenticate LDAP bind requests\&.
.RE
.PP
none
.RS 4
No SASL mechanism will be use to authenticate LDAP bind requests\&.
.RE
.RE
.PP
\fBscope\fR (default: \fIsub\fR)
.RS 4
Specify the scope of the search to be one of
\fIbase\fR
(or
\fIexact\fR),
\fIone\fR
(or
\fIonelevel\fR),
\fIsub\fR
(or
\fIsubstree\fR), to specify a base object, one\-level, or subtree search\&.
.RE
.PP
\fBusetls\fR (default: \fIfalse\fR)
.RS 4
Specifies if automx should use TLS when it connects to the LDAP host\&.
.RE
.SH "SEE ALSO"
.PP
\fBautomx\fR(8),
\fBautomx.conf\fR(5),
\fBautomx_ldap\fR(5),
\fBautomx_script\fR(5),
\fBautomx_sql\fR(5),
\fBautomx-test\fR(1)
.SH "AUTHORS"
.PP
\fBChristian Roessner\fR <\&cr@sys4\&.de\&>
.RS 4
Wrote the program\&.
.RE
.PP
\fBPatrick Ben Koetter\fR <\&p@sys4\&.de\&>
.RS 4
Wrote the documentation\&.
.RE
.SH "NOTES"
.IP " 1." 4
RFC 2195
.RS 4
\%http://tools.ietf.org/rfc/rfc2195.txt
.RE
.IP " 2." 4
RFC 2831
.RS 4
\%http://www.ietf.org/rfc/rfc2831.txt
.RE
.IP " 3." 4
RFC 4422
.RS 4
\%http://tools.ietf.org/rfc/rfc4422.txt
.RE
.IP " 4." 4
RFC 4752
.RS 4
\%http://www.ietf.org/rfc/rfc4752.txt
.RE
